#!/bin/bash
#
# This script will configure an "environment" file with the correct
# environment variables the rest of the scripts will use

SCRIPT_LABEL=$0
log() {
 tmpd=`date "+%F %H:%M:%S"`
 tmp="$tmpd [$SCRIPT_LABEL] $1"
 #echo $tmp >> $LOG
 echo $tmp
}

error() {
 log "ERROR $@"
 #log "$@"
 exit 1
}

usage() {
cat << EOF
usage: $0 options

This script will generate an environment file for use in configuring a deploy of the API system.

OPTIONS:
   -h      Show this message
   -p      (Required) AWS profile
   -r      (Required) AWS region (e.g. us-west-2)
   -e      (Required) Environment name (e.g. staging)
   -k      (Required) Directory containing the SSH keys for the deployment

EOF
}

# parse command line options
while getopts 'hp:r:e:k:' flag; do
  case "${flag}" in
    h) usage
       exit 1 ;;
    p) AWS_PROFILE="${OPTARG}" ;;
    r) AWS_REGION="${OPTARG}" ;;
    e) ENV_NAME="${OPTARG}" ;;
    k) SSH_KEY_DIR="${OPTARG}" ;;
    *) echo "Unexpected option ${flag}"
       usage
       exit 1;;
  esac
done

# validate input
if [[ $AWS_PROFILE == "" ]]; then
    echo "ERROR: AWS profile is a required parameter with the -p option."
    usage
    exit 1;
fi
# validate input
if [[ $AWS_REGION == "" ]]; then
    echo "ERROR: AWS region is a required parameter with the -r option."
    usage
    exit 1;
fi
# validate input
if [[ $ENV_NAME == "" ]]; then
    echo "ERROR: Environment name is a required parameter with the -e option."
    usage
    exit 1;
fi
# validate input
if [[ $SSH_KEY_DIR == "" ]]; then
    echo "ERROR: SSH key directory is a required parameter with the -k option."
    usage
    exit 1;
fi

getExportValue() {
	RETVAL=$(aws --profile $AWS_PROFILE --region $AWS_REGION cloudformation list-exports --query "Exports[?Name=='$1'].Value" --output text)
	if (( $? > 0 )) ; then error "unable to call AWS CLI"; fi
}

# get api_public_jump_public_ip
getExportValue "$ENV_NAME-api-public-jump-PublicIpAddress"
api_public_jump_public_ip=$RETVAL
log "found api_public_jump_public_ip=$api_public_jump_public_ip"

#get api_public_jump_key_pem=$HOME/.ssh/aws/api-staging-us-west-2.pem
getExportValue "$ENV_NAME-api-public-jump-InstanceKeyName"
api_public_jump_key_pem="$SSH_KEY_DIR/$RETVAL.pem"
log "found api_public_jump_key_pem=$api_public_jump_key_pem"

if [ ! -f $api_public_jump_key_pem ]; then
    error "SSH key file not found, please specify containing directory: $api_public_jump_key_pem"
fi

#get api_private_jump_private_ip=10.180.10.101
getExportValue "$ENV_NAME-api-private-jump-PrivateIpAddress"
api_private_jump_private_ip=$RETVAL
log "found api_private_jump_private_ip=$api_private_jump_private_ip"

#get api_private_jump_key_pem=$HOME/.ssh/aws/api-staging-us-west-2-private.pem
getExportValue "$ENV_NAME-api-private-jump-InstanceKeyName"
api_private_jump_key_pem="$SSH_KEY_DIR/$RETVAL.pem"
log "found api_private_jump_key_pem=$api_private_jump_key_pem"

if [ ! -f $api_private_jump_key_pem ]; then
    error "SSH key file not found, please specify containing directory: $api_private_jump_key_pem"
fi

#get staging-JDBCConnectionString
getExportValue "$ENV_NAME-JDBCConnectionString"
api_rds_jdbc_string=$RETVAL
log "found api_rds_jdbc_string=$api_rds_jdbc_string"

#get staging-RDSClusterAddress
getExportValue "$ENV_NAME-RDSClusterAddress"
api_rds_cluster_address=$RETVAL
log "found api_rds_cluster_address=$api_rds_cluster_address"

#get staging-RDSClusterPort
getExportValue "$ENV_NAME-RDSClusterPort"
api_rds_cluster_port=$RETVAL
log "found api_rds_cluster_address=$api_rds_cluster_port"

# output environment
echo "# Environment file - autogenerated by build-script-environment.sh" > environment
echo "#" >> environment
echo "# SSH command to public jump:" >> environment
echo "#   ssh -i $api_public_jump_key_pem ubuntu@$api_public_jump_public_ip" >> environment
echo "#" >> environment
echo "# SSH command to private jump (after key installation):" >> environment
echo "#   ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand=\"ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i $api_public_jump_key_pem ubuntu@$api_public_jump_public_ip nc $api_private_jump_private_ip 22\"  -i $api_private_jump_key_pem ubuntu@$api_private_jump_private_ip" >> environment
echo "#" >> environment
echo "#" >> environment
echo "api_public_jump_public_ip=$api_public_jump_public_ip" >> environment
echo "api_public_jump_key_pem=$api_public_jump_key_pem" >> environment
echo "api_private_jump_private_ip=$api_private_jump_private_ip" >> environment
echo "api_private_jump_key_pem=$api_private_jump_key_pem" >> environment
echo "api_rds_jdbc_string=$api_rds_jdbc_string" >> environment
echo "api_rds_cluster_address=$api_rds_cluster_address" >> environment
echo "api_rds_cluster_port=$api_rds_cluster_port" >> environment

log "completed configuration, wrote environment file:"
cat environment



